qri-io/website

- content/docs/reference/dataset.md
- docs/blog/datasets_are_books/index.html
- docs/blog/index.html
- docs/categories/index.html
- docs/company/index.html
- docs/docs/concepts/content-addressing/index.html
- docs/docs/concepts/index.html
- docs/docs/concepts/names/index.html
- docs/docs/concepts/overview/index.html
- docs/docs/concepts/registries/index.html
- docs/docs/concepts/value_cascade/index.html
- docs/docs/concepts/version_control/index.html
- docs/docs/index.html
- docs/docs/reference/dataset/index.html
- docs/docs/reference/html_templates/index.html
- docs/docs/reference/index.html
- docs/docs/reference/index.xml
- docs/docs/reference/skylark_syntax/index.html
- docs/docs/reference/sylark_functions/index.html
- docs/docs/tutorials/cli_quickstart/index.html
- docs/docs/tutorials/index.html
- docs/docs/tutorials/skylark_transformations/index.html
- docs/download/index.html
- docs/faq/index.html
- docs/index.html
- docs/index.xml
- docs/papers/index.html
- docs/tags/index.html
Changed 'Reproducible' to 'Reuseable'
> FAIR data correction

- config.yaml
- content/docs/reference/_index.md
- content/docs/reference/cli_commands.md
- docs/company/index.html
- docs/docs/reference/cli_commands/index.html
- docs/docs/reference/dataset/index.html
- docs/docs/reference/html_templates/index.html
- docs/docs/reference/index.html
- docs/docs/reference/index.xml
- docs/docs/reference/skylark_syntax/index.html
- docs/docs/reference/sylark_functions/index.html
- docs/docs/tutorials/cli_quickstart/index.html
- docs/docs/tutorials/index.xml
- docs/faq/index.html
- docs/index.html
- docs/index.xml
- docs/sitemap.xml
Added CLI documentation that was generated by cobra and stiched together
> docs(CLI): added command line docs to reference section

- .gitattributes
GUYZ, u can make github ignore generated files in PRs.
https://medium.com/@clarkbw/managing-generated-files-in-github-1f1989c09dfd
> chore(git): ignore generated files in PRs

- docs/download/index.html
updated link to CLI 0.5.0 to 0.5.2 in the download link
> updated link to CLI 0.5.0 to 0.5.2

- content/download.md
- docs/download/index.html
Updated: frontend 0.2.0 > 0.3.0
Updated CLI: 0.5.1 > 0.5.2
> Updated Links to qri front end and CLI Downloads

- config.yaml
- content/docs/reference/cli_commands.md
- docs/css/highlight.theme.tomorrow.css
- docs/css/qri.css
- docs/docs/reference/cli_commands/index.html
- docs/docs/reference/dataset/index.html
- docs/docs/reference/index.xml
- docs/docs/reference/skylark_syntax/index.html
- docs/docs/reference/starlib/index.html
- docs/docs/tutorials/cli_quickstart/index.html
- docs/docs/tutorials/python_quickstart/index.html
- docs/docs/tutorials/skylark_transformations/index.html
- docs/index.xml
- themes/qri_io/static/css/highlight.theme.tomorrow.css
Not perfect, but big improvement!
> style(codeblocks): add syntax highlighting for code blocks

- content/download.md
- docs/index.xml
- docs/sitemap.xml
Updated link to point to 0.5.4 for CL
> Updated link to point to 0.5.4

- content/download.md
- docs/download/index.html
Updated URLs to point to 0.5.0 (Front End)
> Updated URLs to point to 0.5.0 (Front End)

- content/download.md
Updated Link to point to 0.5.5 (back end)
> Updated Link to point to 0.5.5

- docs/download/index.html
Can someone make sure i didn't F anything up in the upper section of the diff?....
> Update to point urls to 0.5.2 (FE) and 0.5.6 (BE)

- config.yaml
- content/_index.md
- content/about.md
- docs/about/index.html
- docs/blog/datasets_are_books/index.html
- docs/blog/index.html
- docs/blog/unit_test_performance/index.html
- docs/categories/index.html
- docs/contact/index.html
- docs/docs/reference/starlark_examples/index.html
- docs/docs/reference/starlib_qri_ds/index.html
- docs/download/index.html
- docs/faq/index.html
- docs/index.html
- docs/index.xml
- docs/legal/index.html
- docs/legal/privacy_policy/index.html
- docs/legal/tos/index.html
- docs/papers/index.html
- docs/sitemap.xml
- docs/tags/concepts/index.html
- docs/tags/content-addressing/index.html
- docs/tags/index.html
- docs/tags/performance/index.html
- docs/tags/testing/index.html
> Tying About page to home mast.

- content/download.md
updated link to download 0.7.0.
> 0.7.0 Updates

- content/docs/tutorials/frontend.md
- docs/company/index.html
- docs/docs/concepts/content-addressing/index.html
- docs/docs/concepts/dataset/index.html
- docs/docs/concepts/distributed-storage/index.html
- docs/docs/concepts/index.html
- docs/docs/concepts/names/index.html
- docs/docs/concepts/overview/index.html
- docs/docs/index.html
- docs/docs/reference/cli_commands/index.html
- docs/docs/reference/dataset/index.html
- docs/docs/reference/index.html
- docs/docs/reference/starlark_examples/index.html
- docs/docs/reference/starlark_syntax/index.html
- docs/docs/reference/starlib/index.html
- docs/docs/reference/starlib_qri_ds/index.html
- docs/docs/tutorials/cli_quickstart/index.html
- docs/docs/tutorials/frontend/index.html
- docs/docs/tutorials/index.html
- docs/docs/tutorials/index.xml
- docs/docs/tutorials/starlark_transformations/index.html
- docs/index.xml
- docs/sitemap.xml
embedded the videos ramfox filmed into a new tutorials page
> 20190214 tutorials fe

- content/docs/concepts/dataset.md
- docs/blog/a_better_mousetrap_podcast/index.html
- docs/blog/datasets_are_books/index.html
- docs/docs/concepts/dataset/index.html
- docs/docs/concepts/index.xml
- docs/index.xml
> fix text height on dataset page

- content/download.md
- docs/blog/datasets_are_books/index.html
- docs/blog/mlb_homeruns/index.html
- docs/blog/unit_test_performance/index.html
- docs/docs/reference/cli_commands/index.html
- docs/download/index.html
> chore(download): electron app version bump

- content/about.md
- content/download.md
Added CWhong bio to about page and updated frontend download link to point to 0.7.2
> CWhong Bio update & 0.7.2 link

- .circleci/config.yml
Updates circleci config to ignore commits on gh-pages
> chore: ignore gh-pages commits in ci config

- content/about.md
updated about section to fix part of CW's bio (typo & text block flip)
> Update to CW bio

- content/about.md
- content/blog/mlb_homeruns.md
- content/docs/_index.md
- content/jobs.md
- themes/qri_io/layouts/partials/footer.html
added the UI/UX Job description to a new page (Qrio/jobs).
> Jobdescriptions

- content/jobs.md
added description for jobs page
> Jobs Page Description

- content/jobs.md
I reinstated layout format for the page to render correctly.
> Reinstated layout

- readme.md
`Pull request` --> `pull request`
> Very, very, so smol, typo

- content/about.md
fixed DT link and minor changes
> fixed DT link and minor changes

- content/beta.md
designed a simple page for driving users to sign up to be Qri Beta testers.
> draft page for Qri.io/beta

- content/beta.md
Adds a blurb saying when we'll contact beta testers who sign up.
Fixes a markdown quirk that was causing asterisks not to be displayed.
> amend beta tester content, fix broken asterisks

- content/docs/concepts/ipfs_to_qri.md
Couldn't resist.
Also 👋!
- Eric Smarty-a** Ronne, Protocol Labs
> Remedies a misspelting

- content/download.md
updated our download page to point to Qri Desktop instead of Qri Frontend
> Download qd010

- content/desktop/getting-started.html
corrected link to blue download button on getting started
> Blue download button fix

- content/blog/community_calendar.md
- content/desktop/_index.md
Drafted a Community Calendar blog post with an embedded calendar and description of our bi-weekly calls.
> Community Calendar blog post

- content/legal/privacy_policy.md
coded up page reflecting latest privacy policy language
> Drafted privacy policy page

- gatsby-config.js
- package.json
- yarn.lock
Adds `gatsby-plugin-google-analytics` and our GA tracking code
> feat: add gatsby-plugin-google-analytics

- src/components/ExternalLink.js
- src/pages/download.js
Adds a custom analytics event to the download page links
> feat: add ga custom event for download

- src/components/Footer.js
Looking at the site (lead there from the IPFS newsletter) and noticed a tiny typo in the footer.
> Tiny typo fix in footer

- content/docs/reference/cli_commands.md
- content/docs/reference/logbook.md
Fixes broken anchor links, broken header formatting, one typo.
> fix: formatting and broken anchor links

- content/docs/getting-started/qri-cli-quickstart.md
Document how to connect with an existing Qri Cloud account, copy edits.
> fix: doc edits

- src/components/sidebar/index.js
> add docs home link to top of docs sidebar

- content/docs/dataset-components/body.md
- content/docs/getting-started/what-is-qri.md
- content/docs/integrating-qri/working-directories.md
- content/docs/reference/qri-system-files.md
- content/docs/working-with-datasets/collection.md
- content/docs/working-with-datasets/publishing.md
- src/scss/_main.scss
- src/scss/_starter.css
Updates various content pages.  Adds margin around code blocks and `InfoBlock` elements to have consistent spacing with <p> tags.
> various content updates, one css fix

- content/docs/dataset-components/transform.md
- content/docs/reference/starlib.md
- content/docs/starlark/examples.md
- content/docs/starlark/introduction.md
- content/docs/starlark/runtime.md
- gatsby-node.js
- scripts/outline_starlib_docs_template.md
- scripts/update_starlib.sh
lots more to do, but this is an improvement IMHO
> starlark docs cleanup work

- config.js
- src/components/Footer.js
Adds links to qri.cloud in header and footer
> feat: add cloud links to header and footer

- content/docs/dataset-components/transform.md
- content/docs/getting-started/qri-cli-quickstart.md
- content/docs/starlark/introduction.md
- content/docs/starlark/starlib.md
Typos, copy edits, added `bsoup` docs.
> Starlark corrections

- src/components/FeaturedDataset.js
- src/scss/homepage.scss
fixes the styling for titles on the blog post cards
> fix: restore blog title styling

- src/components/BlogCard.js
- src/components/FeaturedDataset.js
- src/components/Footer.js
- src/pages/index.js
Adds analytics events to homepage exit points (buttons, links, featured dataset cards, blog cards, & form submissions)
Adds analytics events to `Footer` social media links
> feat: add analytics events to all homepage exits

- src/pages/faq.md
> fix: update faq

- content/docs/transforms/quickstart.md
> fix: correct "Example Transform Scripts" link

- content/docs/getting-started/qri-cli-quickstart.md
replace removed `--password` flag with correct `--email` flag
Closes #193
> fix: document new flag for `registry prove`

- src/pages/index.js
add translucent `background-color` to subhead to fix contrast
in edge cases
Closes #207
> fix: increase contrast on "Qri helps..." subhead

- src/pages/index.js
update data stories
use curly apostrophes
closes #221
> fix: update 'Data Stories' section on home pages

- content/docs/transforms/runtime.md
add warning block
curl apostrophes
tighten copy
fixes #212
> fix: update starlark secrets example

- src/scss/homepage.scss
added missing styles
closes #228
> fix: readd missing style to restore images

- src/pages/download.js
upgrade version number on desktop downloads page to latest v0.4.4
> refactor: upgrade version number on desktop downloads page to latest v0.4.4

- content/docs/getting-started/qri-cli-quickstart.md
- content/docs/getting-started/qri-desktop-quickstart.md
- content/docs/working-with-datasets/publishing.md
- src/pages/docs.js
- src/pages/download.js
- src/pages/jobs/archive-job-data-research-assistant.md
add 'Contact hello@qri.io about private repos'
add 'Pushing in Qri Desktop' to `publishing`
remove qri cloud alpha warnings
use curly apostrophes
change `qri publish` to push
closes #240, #241
> docs: update `qri publish` to `qri push`

- gatsby-node.js
> add /ODW2021 redirect link

- config.js
- gatsby-config.js
- package.json
- src/components/BreadCrumbs.js
- src/components/DocsColumns.js
- src/components/DocsContent.js
- src/components/DocsContentWide.js
- src/components/DocsSectionLandingPage.js
- src/layouts/DocsSectionLandingPageLayout.js
- yarn.lock
> Add breadcrumbs

- src/components/DocsCard.js
- src/components/DocsColumns.js
- src/components/DocsContent.js
- src/components/DocsSectionLandingPage.js
- src/components/HeaderLink.js
- src/components/RightSidebar.js
- src/components/sidebar/tree.js
- tailwind.config.js
- add zoom effect to docs nav donut icons
- ensure that docs group descriptions show on section landing pages
- fix duplicate key warning on docs section landing 
- fix: text-overflow in DocsCard
- show doc contents (right sidebar) above text on small screens
> Style tweaks

- src/pages/index.js
- updates the homepage metrics
- stores them as a separate object for ease of update, and uses numeral.js for formatting.
> chore: update hardcoded metrics

- content/docs/reference/qri-http-api/json-api-spec.md
- gatsby-node.js
- src/layouts/DocsContentLayout.js
> fix: redoc layout

- .gitignore
- src/components/search/SearchModal.js
- src/pages/docs.js
- static/img/new-docs/yellow-aura-mobile.svg
added responsive UI to docs page. Fixed the UI of search modal
fixes #331
fixes #329
> fix: added responsive UI to docs page. Fixed the UI of search modal

- package.json
- src/components/HeaderLink.js
- src/components/Icon.js
- src/components/icon/Check.js
- src/components/icon/Copy.js
- src/components/mdxComponents/codeBlock.js
- src/components/snippets/Snippet.js
- src/components/snippets/SnippetCard.js
- src/components/snippets/SnippetEditor.js
- src/scss/style.scss
- tailwind.config.js
- yarn.lock
- Changes the styles for `SnippetCard` based on @tefyzambrano feedback
- Adds a quick copy link which appears when hovering the CodeBlock
> feat: style tweaks, add quick copy button
