qri-io/website

content/_index.md
docs/blog/datasets_are_books/index.html
docs/blog/index.html
docs/categories/index.html
docs/company/index.html
docs/docs/concepts/content-addressing/index.html
docs/docs/concepts/index.html
docs/docs/concepts/names/index.html
docs/docs/concepts/overview/index.html
docs/docs/concepts/registries/index.html
docs/docs/concepts/set_value_cascade/index.html
docs/docs/concepts/version_control/index.html
docs/docs/index.html
docs/docs/reference/dataset/index.html
docs/docs/reference/glossary/index.html
docs/docs/reference/html_templates/index.html
docs/docs/reference/index.html
docs/docs/reference/skylark_syntax/index.html
docs/docs/tutorials/cli_quickstart/index.html
docs/docs/tutorials/index.html
docs/docs/tutorials/skylark_transformations/index.html
docs/download/index.html
docs/faq/index.html
docs/index.html
docs/papers/index.html
docs/tags/index.html

Capitalized some Qs wherever they began 'paragraphs' for consistency's sake. Also eliminated some duplicate spaces.

Minor grammatical changes

---

themes/qri_io/static/css/docs.css

On some docs pages, we have absolutely positioned content. Because the navigation comes *before* the content, that means content shows up in front of the menu, like this:
I set an explicit z-index on the menu content that is just below the menu toggle. Ideally, I’d use CSS custom properties so there aren’t a bunch of magical z-index values floating around the CSS file, but I’m not sure what browsers you’re aiming to be compatible with.

Bump up the z-index of docs menu on small screens

---

content/docs/reference/cli_commands.md
content/docs/tutorials/cli_advanced_starlark_transformations.md

Ran docrun over just two of our markdown files to see how it did. Fixed a few problems, but also added a bunch of TODOs to come back to later, once docrun has gained some more features. This gives some good indication of how much of qri we need to be able to mock-out in order to run all of these examples.

Correct some examples using docrun

---

.circleci/config.yml

build script needs to write a file called CNAME to the publish directory.
More info: https://github.com/tschaub/gh-pages/issues/213#issuecomment-463283771

fix(CNAME): fix ci-pusher wiping out qri.io domain name

---

config.js
content/docs/getting-started/qri-desktop-quickstart.md

"Edit on Github" links were going to the now-archived `wesbite-refresh` repo.
This PR updates these links, and also fixes a bad link to qri.cloud.

fix: update github edit url and fix one link

---

content/docs/reference/ipfs_to_qri.md

Fix capitalization in sentence within the Qri documentation relating to IPFS-to-Qri.

fix(docs): Capitalization correction

---

src/components/Footer.js

Updates footer link for "Download Qri CLI" to point to the github releases page.

fix: update footer link for CLI

---

gatsby-node.js

Adds a redirect for dead link: https://qri.io/docs/reference/dataset-specification/

fix: add redirect for dataset spec

---

src/pages/data-stories/brooklyn-bus-times.md

Adds a link to data logger code in the brooklyn bus times data story

fix: add link to logging script code

---

content/docs/getting-started/qri-cli-quickstart.md

Related to qri-io/qri#1111, adds Brew install instructions to the CLI quick start page.

Add Brew install instructions to CLI directions

---

content/docs/reference/installing-qri-cli.md

Adds a docs article for installing the qri binary (via desktop, build, or from source) and instructions on how to set PATH so that the qri command is available in the terminal.

docs for installing the qri binary and setting path

---

content/docs/getting-started/qri-cli-quickstart.md

@b5 said the page is missing until doc generation in qri-io/qri is fixed.
Link needs to be readded after doc generation is fixed.
Issue for future rollback, #177.

Remove link to cli-manual

---

gatsby-node.js

This'll allow for a nice-looking one-liner install that also passes through a domain name we control over TLS: https://qri.io/install.sh
This sets the stage for installing the qri CLI with a one-liner. based directly on https://deno.land
If this works we can add the following instruction for installing qri CLI for linux & os x:
```
curl -fsSL https://qri.io/install.sh | sh
```

feat(install.sh): add /install.sh redirect

---

content/docs/transforms/examples.md

Adds a dirt-simple transform example showing how to download a CSV from the web and set the body without parsing it or doing any transformation.

Add simple transform example

---

gatsby-config.js
package.json
src/components/DatasetSummary.js
src/components/FeaturedDatasets.js
src/components/Icon.js
src/components/ListItem.js
src/components/RelativeTimestamp.js
src/pages/index.js
src/scss/_starter.css
src/scss/homepage.scss
yarn.lock

**DO NOT MERGE UNTIL https://github.com/qri-io/cloud/pull/341 IS DEPLOYED**
(Netlify checks will fail until the new endpoint is live, gatsby needs this data to build the site.)
This PR replaces the hard-coded featured datasets cards on the front page, using a new JSON feed from qri.cloud to get the current featured datasets.  
Several react components are also ported from the qri cloud frontend codebase: `FeaturedDatasets`, `ListItem`, `Icon`, `DatasetSummary`, `RelativeTimestamp`.
SCSS for these cards is also ported from qri.cloud, so they will look identical on both sites.

feat: add dynamic featured datasets from qri.cloud

---

src/components/DatasetSummary.js

change relative links to absolute to qri.cloud
closes #230

fix: correct broken links for featured datasets

---

src/pages/download.js

need to restore normal `windowsDownloadUrl` (currently commented out
code) when the windows release goes live on monday

desktop version bump to 0.4.3

---

content/docs/reference/qri_python_commands.md

Adding in the auto-generated docs from the pydoc-markdown script we just included in the qri-python project. 
The intent here is that this page will be periodically updated by running the script in qri-python & copypasta-ing here.

docs(qri-python): add docs for qri python client

---

src/pages/download.js

this only changes the download link for the macos version, we will have to update when the windows release is added to the releases page.

fix: upgrade version number on desktop downloads page to latest v0.4.4

---

content/docs/getting-started/qri-cli-quickstart.md

With qri 0.9.13 I had problems initializing a dataset. I've figured out that there isn't a `--source-body-path` parameter anymore and I need to use `--body` instead.

Changed to --body parameter for qri init

---

gatsby-config.js
gatsby-node.js
package.json
src/components/DatasetSummary.js
src/components/FeaturedDatasets.js
src/pages/index.js
src/scss/_main.scss

Fixes a build error related to featured datasets.  Featured datasets are pulled from qri cloud as JSON and converted to graphQL nodes for use in Gatsby.  For some reason, this process would fail when `structure.length` was a large integer, causing a node heap error.  
This PR removes the plugin `gatsby-source-apiserver` in favor of custom code in `gatsby-node.js`.  It effectively makes the same API call, but allows us to coerce `structure.length` into a string to avoid the error.
Adds a featured embedded youtube video and a simple list of additional videos with thumbnails and titles.

Fix featured datasets, Add Youtube Embeds

---

gatsby-config.js
gatsby-node.js
src/components/DocsContent.js
src/components/Header.js
src/components/search/SearchModal.js
src/pages/index.js
tailwind.config.js

Cleans up several build warnings
- adds purging of unused tailwind css
- cleans up unused imports, etc that eslint was yelling about
- removes unused graphql queries for siteMetadata (no longer needed as `docsSections` is imported from config outside of graphql)

Clean up build warnings

---

gatsby-config.js
src/components/Header.js
src/components/search/CustomHits.js
src/components/search/SearchModal.js

Restores `gatsby-plugin-algolia` which powers search indexing, updates search results components to reflect recent changes to `docsSection` schema.
Adds search icon to mobile nav, tweak styling for search modal on mobile

Clean up search

---

gatsby-config.js
src/scss/style.scss
tailwind.config.js

- Adds two colors to tailwind purge `safeList` (they were only used in js code config objects, not in JSX, so were not available in the built site)
(Closes #293)
- Manually offset `target` elements so that right sidebar (contents) links will scroll to the correct spot on the page (Closes #275)

Various fixes

---

content/docs/reference/starlark-packages/bsoup.md
content/docs/reference/starlark-packages/dataframe.md
content/docs/reference/starlark-packages/geo.md
content/docs/reference/starlark-packages/html.md
content/docs/reference/starlark-packages/http.md
content/docs/reference/starlark-packages/re.md
content/docs/reference/starlark-packages/time.md
content/docs/reference/starlark-packages/xlsx.md
content/docs/reference/starlark-packages/zipfile.md
src/components/RightSidebar.js

Depends on changes in https://github.com/qri-io/starlib/pull/151
Closes #341 
Along with a change to the docs template file in starlib, this changes the heading tags in starlark docs so that the correct hierarchy can be shown in starlark package docs tables of contents:
Note: We only show "third tier" items under the `Types` top-level heading.  This is hard coded and can be changed if we need to expand it to other sections. (If left to always show, we end up seeing "parameters" as a third-tier item under top-level functions, which is not something we want.

fix: clarify hierarchy in starlark docs right sidebar
